process:
  bam: data/bam
  junction: data/junc
  lc: leafcutter
threshold:
  sites_initial: 4
  runs_initial: 100
  sites_quality: 10
  runs_quality: 100
io:
  log_scale_histogram: false
  use_label: true
  label_file: data/label.csv
  truth_column: finaltype
  run_column: Run
  output_path: process_result
impute:
  num_iteration: 3
  knn: 5
cluster:
  pca_dimension: 20
  dimension_reduction_method: umap
  cluster_algorithm: spectral
  num_cluster: 3

